apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  storageClassName: local1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook"