// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gevinzone/basic-go/live/webook/internal/repository"
	"github.com/gevinzone/basic-go/live/webook/internal/repository/cache"
	"github.com/gevinzone/basic-go/live/webook/internal/repository/dao"
	"github.com/gevinzone/basic-go/live/webook/internal/service"
	"github.com/gevinzone/basic-go/live/webook/internal/web"
	"github.com/gevinzone/basic-go/live/webook/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	profileDAO := dao.NewProfileDAO(db)
	userWithProfileDAO := dao.NewUserWithProfileDAO(db, userDAO, profileDAO)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, profileDAO, userWithProfileDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSmsService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
